"""Battery design data from ``powercfg /batteryreport /xml``.

The ``BatteryStaticData`` WMI class (design capacity) frequently fails without administrator
rights. The battery report is generated by the Windows power subsystem and is readable by a normal
user, so it is the preferred source for design capacity and chemistry.
"""

from __future__ import annotations

import os
import subprocess
import tempfile
import xml.etree.ElementTree as ET  # parsing a file we just generated locally
from dataclasses import dataclass
from pathlib import Path

from app.errors import DriverUnavailableError, HardwareMissingError, MalformedValueError

_NS = "{http://schemas.microsoft.com/battery/2012}"


@dataclass(frozen=True, slots=True)
class BatteryReportEntry:
    battery_id: str
    manufacturer: str | None
    chemistry: str | None
    design_capacity_mwh: int | None
    full_charge_capacity_mwh: int | None
    cycle_count: int | None


def _int_or_none(text: str | None) -> int | None:
    if text is None or not text.strip():
        return None
    try:
        return int(text.strip())
    except ValueError as exc:
        raise MalformedValueError(f"Unexpected battery report value {text!r}") from exc


def parse_battery_report(xml_text: str) -> list[BatteryReportEntry]:
    root = ET.fromstring(xml_text)  # noqa: S314  (trusted: produced by powercfg on this host)
    batteries = root.find(f"{_NS}Batteries")
    if batteries is None:
        return []
    entries: list[BatteryReportEntry] = []
    for bat in batteries.findall(f"{_NS}Battery"):

        def text(tag: str, node: ET.Element = bat) -> str | None:
            child = node.find(f"{_NS}{tag}")
            return child.text if child is not None else None

        entries.append(
            BatteryReportEntry(
                battery_id=(text("Id") or "battery").strip(),
                manufacturer=text("Manufacturer"),
                chemistry=text("Chemistry"),
                design_capacity_mwh=_int_or_none(text("DesignCapacity")),
                full_charge_capacity_mwh=_int_or_none(text("FullChargeCapacity")),
                cycle_count=_int_or_none(text("CycleCount")),
            )
        )
    return entries


def read_battery_report(timeout_s: float = 20.0) -> list[BatteryReportEntry]:
    fd, path = tempfile.mkstemp(suffix=".xml", prefix="ldt-battery-")
    os.close(fd)
    try:
        try:
            proc = subprocess.run(
                ["powercfg", "/batteryreport", "/xml", "/output", path],
                capture_output=True,
                timeout=timeout_s,
                check=False,
                creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
            )
        except FileNotFoundError as exc:
            raise DriverUnavailableError("powercfg.exe not found") from exc
        except subprocess.TimeoutExpired as exc:
            raise DriverUnavailableError(
                f"powercfg battery report timed out after {timeout_s:.0f} s"
            ) from exc
        if proc.returncode != 0:
            raise DriverUnavailableError(f"powercfg exited with {proc.returncode}")
        xml_text = Path(path).read_text(encoding="utf-8", errors="replace")
    finally:
        Path(path).unlink(missing_ok=True)
    entries = parse_battery_report(xml_text)
    if not entries:
        raise HardwareMissingError("Battery report lists no batteries")
    return entries
